Feature/ensamble
KWEBofficial/What2Eat-server pull request #16
Opened 2024-01-10 13:02 UTC by hmin27

모든 코드 합한 버전입니다. 
url 생성, participant에 투표 생성자 추가 부분이 수정되었습니다. 그 외 로직은 모두 동일합니다. 

회원가입부터 result 보는 것까지 모두 테스트해보면 될 것 같습니다!

2024-01-10 13:45 UTC, rla-suedeng requested changes
logout router만 추가하면 될 거 같아용~! 테스트 전체적으로 잘 됩니다!

2024-01-10 15:46 UTC, cympyc1785 approved these changes
LGTM!

2024-01-11 02:54 UTC, JeongYeonSeung approved these changes
LGTM!! insomnia에서 전체적으로 테스트 다 잘 되는 것 확인했습니다! 고생많으셨어용
다만 restaurant entity에서 restaurant이랑 location이 OneToOne이 아닌 ManyToOne인 것 같아서, 그 부분만 수정하면 될 것 같습니다!

2024-01-11 04:43 UTC, strn18 approved these changes
LGTM! 나중에 로그인/게스트 여부 확인 등 접근 권한 설정만 하면 될 것 같아요!

2024-01-11 06:18 UTC, merged